export interface AppWalkthroughItem {
  appName: string;
  steps: string[];
  fieldLabelHint: string;
}

export interface TerminologyItem {
  id: string;
  numberIndex: number;
  term: string;
  shortWhatItMeans: string;
  whereToFindIt: string;
  whyNivaranNeedsIt: string;
  appWalkthrough?: AppWalkthroughItem[];
}

export interface RedFlagDecoderItem {
  id: string;
  scenario: string;
  category: string;
  whyThisMatters: string;
  whatMayBeHappening: string;
  whatNotToDo: string;
  whatToDoInstead: string;
}

export interface CommonConfusionItem {
  id: string;
  question: string;
  answer: string;
  practicalTip: string;
}

export interface MythVsRealityItem {
  id: string;
  myth: string;
  reality: string;
  impact: string;
}

export interface EvidencePreservationItem {
  id: string;
  name: string;
  category: 'payment' | 'communication' | 'identifier';
  whyItMatters: string;
  whereToFindIt: string;
  howToSaveIt: string;
}

// -------------------------------------------------------------
// 1. FINANCIAL FRAUD TERMINOLOGY (21 Terms)
// -------------------------------------------------------------
export const TERMINOLOGY_DATABASE: TerminologyItem[] = [
  {
    id: 'utr',
    numberIndex: 1,
    term: 'UTR (Unique Transaction Reference)',
    shortWhatItMeans: 'A 12-digit central banking identifier assigned by the National Payments Corporation of India (NPCI) or RBI to uniquely track an electronic fund transfer across all Indian banks.',
    whereToFindIt: 'Found on the payment confirmation screen in your UPI app, transaction details receipt, debit SMS alert, or bank statement.',
    whyNivaranNeedsIt: 'The 12-digit UTR is the mandatory primary key required by the 1930 Helpline and bank fraud cells to trace and place an inter-bank lien (freeze) on the beneficiary account before funds are siphoned.',
    appWalkthrough: [
      {
        appName: 'Google Pay',
        steps: ['Open Google Pay', 'Tap "See transaction history"', 'Tap the disputed transaction', 'Look for "UPI transaction ID"'],
        fieldLabelHint: 'Look for a field labelled "UPI transaction ID" (12 digits, e.g. 423719820491)'
      },
      {
        appName: 'PhonePe',
        steps: ['Open PhonePe', 'Tap "History" at the bottom right', 'Select the disputed payment', 'Tap "Transaction Details"'],
        fieldLabelHint: 'Look for a field labelled "UTR" or "Transfer Details > UTR No."'
      },
      {
        appName: 'Paytm',
        steps: ['Open Paytm', 'Tap "Balance & History"', 'Tap the disputed transaction', 'Look under UPI Reference Details'],
        fieldLabelHint: 'Look for a field labelled "UPI Ref No." or "UTR"'
      },
      {
        appName: 'Netbanking / Debit SMS',
        steps: ['Check the official bank debit alert SMS', 'Or download your bank statement PDF'],
        fieldLabelHint: 'Look for "UPI/423719820491/..." or "RRN: 423719820491"'
      }
    ]
  },
  {
    id: 'rrn',
    numberIndex: 2,
    term: 'RRN (Retrieval Reference Number)',
    shortWhatItMeans: 'A 12-digit reference number generated by payment switches for card and IMPS/UPI network routing. In UPI payments, RRN and UTR are often identical 12-digit numbers.',
    whereToFindIt: 'On ATM charge slips, POS card machine receipts, netbanking transfer logs, and bank statement line items.',
    whyNivaranNeedsIt: 'Bank nodal desks use RRNs to trace inter-bank card settlements and dispute chargeback claims with Visa/Mastercard/RuPay.',
    appWalkthrough: [
      {
        appName: 'Bank Mobile App',
        steps: ['Log in to Bank App', 'Navigate to Account Statement / Activity', 'Expand the disputed transaction row'],
        fieldLabelHint: 'Look for "RRN" or "Reference No."'
      }
    ]
  },
  {
    id: 'upi-id-vpa',
    numberIndex: 3,
    term: 'UPI ID / VPA (Virtual Payment Address)',
    shortWhatItMeans: 'A unique virtual email-like identifier (e.g. username@bankhandle) that maps directly to a bank account without revealing the actual account number.',
    whereToFindIt: 'Displayed on the payment receipt under recipient details (e.g. merchant@okaxis, user@ybl, name@oksbi).',
    whyNivaranNeedsIt: 'Identifies the beneficiary destination node where the disputed funds arrived, allowing 1930 / I4C to flag the recipient handle in the national cyber fraud database.',
    appWalkthrough: [
      {
        appName: 'UPI Apps (GPay, PhonePe, Paytm)',
        steps: ['Select the transaction in history', 'View the "Paid to" or "To" header'],
        fieldLabelHint: 'Look for the address containing an "@" symbol (e.g. discom.billupdate.982@okaxis)'
      }
    ]
  },
  {
    id: 'tx-id',
    numberIndex: 4,
    term: 'Transaction ID (App-Specific ID)',
    shortWhatItMeans: 'An internal alphanumeric identifier generated specifically by the payment application (Google Pay, PhonePe, Paytm, CRED) for its internal support ticketing.',
    whereToFindIt: 'At the top or bottom of the in-app digital payment receipt (e.g. T2608241028148921083921).',
    whyNivaranNeedsIt: 'Used when filing in-app dispute complaints with payment aggregators and app-level consumer grievance desks.',
    appWalkthrough: [
      {
        appName: 'Payment Apps',
        steps: ['Open payment receipt', 'Scroll to the bottom'],
        fieldLabelHint: 'Look for "Transaction ID", "Order ID", or "Payment ID"'
      }
    ]
  },
  {
    id: 'beneficiary',
    numberIndex: 5,
    term: 'Beneficiary',
    shortWhatItMeans: 'The individual, business, or entity that received the funds transferred from your bank account.',
    whereToFindIt: 'On your payment receipt as the registered name of the payee or merchant.',
    whyNivaranNeedsIt: 'Helps cross-verify whether the recipient was an individual personal savings account or a registered commercial merchant.'
  },
  {
    id: 'ifsc',
    numberIndex: 6,
    term: 'IFSC (Indian Financial System Code)',
    shortWhatItMeans: 'An 11-character alphanumeric code that uniquely identifies a specific bank branch in India (e.g. HDFC0001234).',
    whereToFindIt: 'On your bank cheque book, passbook first page, netbanking account overview, or statement header.',
    whyNivaranNeedsIt: 'Identifies your home branch and the recipient bank branch for inter-bank legal recall notices.'
  },
  {
    id: 'account-number',
    numberIndex: 7,
    term: 'Account Number (Masked / Full)',
    shortWhatItMeans: 'The unique numeric code assigned by your bank to your savings or current account. For security, statements often mask all but the last 4 digits (e.g. *9104).',
    whereToFindIt: 'On your passbook, cheque leaf, or debit SMS notifications.',
    whyNivaranNeedsIt: 'Required by your bank to log formal dispute tickets and verify originating debit transactions.'
  },
  {
    id: 'merchant',
    numberIndex: 8,
    term: 'Merchant / Merchant Name',
    shortWhatItMeans: 'A commercial entity registered with a bank or payment aggregator to accept customer payments for goods or services.',
    whereToFindIt: 'On the payment confirmation page under the recipient display name.',
    whyNivaranNeedsIt: 'Fraudsters often register deceptive merchant names (e.g. "POWER BILL DEPT") on aggregators to mislead victims.'
  },
  {
    id: 'authorization',
    numberIndex: 9,
    term: 'Authorization',
    shortWhatItMeans: 'The explicit consent given by an account holder to permit a financial transaction, typically via entering an OTP, UPI PIN, or biometric check.',
    whereToFindIt: 'The authentication prompt triggered during payment checkout.',
    whyNivaranNeedsIt: 'Banks evaluate customer liability based on whether authorization was voluntary or procured through deceptive social engineering.'
  },
  {
    id: 'otp',
    numberIndex: 10,
    term: 'OTP (One-Time Password)',
    shortWhatItMeans: 'A time-sensitive, single-use numeric code (usually 4 or 6 digits) sent to your registered mobile phone or email to authenticate a single transaction or login.',
    whereToFindIt: 'Delivered via SMS text message or email notification.',
    whyNivaranNeedsIt: 'CRITICAL RULE: Legitimate banks and support agents NEVER ask for your OTP. Sharing an OTP allows attackers to authorize debits or hijack accounts.'
  },
  {
    id: 'upi-pin',
    numberIndex: 11,
    term: 'UPI PIN (Personal Identification Number)',
    shortWhatItMeans: 'A 4 or 6-digit confidential passcode created by you on your mobile phone to authorize fund transfers from your linked bank account.',
    whereToFindIt: 'Typed exclusively on the secure NPCI black/white keyboard screen on your phone.',
    whyNivaranNeedsIt: 'FUNDAMENTAL RULE: Typing your UPI PIN ALWAYS DEBITS money. You NEVER enter your UPI PIN to receive money, get a refund, or verify your account.'
  },
  {
    id: 'debit',
    numberIndex: 12,
    term: 'Debit',
    shortWhatItMeans: 'An accounting entry representing money taken out of your bank balance (funds leaving your account).',
    whereToFindIt: 'Indicated with a minus sign (-) or marked "Dr." in your bank passbook and SMS alerts.',
    whyNivaranNeedsIt: 'Defines the quantitative loss incurred during the cyber incident.'
  },
  {
    id: 'credit',
    numberIndex: 13,
    term: 'Credit',
    shortWhatItMeans: 'An accounting entry representing money added to your bank balance (funds arriving into your account).',
    whereToFindIt: 'Indicated with a plus sign (+) or marked "Cr." in bank statements.',
    whyNivaranNeedsIt: 'Used to verify whether trial refunds or partial reversals were actually deposited into your account.'
  },
  {
    id: 'chargeback',
    numberIndex: 14,
    term: 'Chargeback',
    shortWhatItMeans: 'A formal dispute process initiated by an issuing bank against an acquiring merchant bank to forcibly reverse an unauthorized card transaction.',
    whereToFindIt: 'Filed through your card issuer bank grievance portal.',
    whyNivaranNeedsIt: 'The primary recovery tool for credit and debit card fraud under card network (Visa/Mastercard/RuPay) dispute frameworks.'
  },
  {
    id: 'dispute',
    numberIndex: 15,
    term: 'Dispute',
    shortWhatItMeans: 'A formal challenge submitted by a customer to a bank or financial institution stating that a recorded transaction was unauthorized or fraudulent.',
    whereToFindIt: 'Raised via bank customer care, netbanking portal, or physical branch submission.',
    whyNivaranNeedsIt: 'Starts the statutory regulatory clock for bank investigation under RBI consumer protection circulars.'
  },
  {
    id: 'complaint-ref',
    numberIndex: 16,
    term: 'Complaint Reference Number (Ticket ID)',
    shortWhatItMeans: 'A unique alphanumeric reference generated by your bank (e.g. HDFC-98127) upon formally recording a fraud complaint.',
    whereToFindIt: 'Sent in bank acknowledgement SMS or email after lodging a grievance.',
    whyNivaranNeedsIt: 'Mandatory reference required to escalate unresolved complaints to the Bank Principal Nodal Officer and RBI Ombudsman.'
  },
  {
    id: 'ack-number',
    numberIndex: 17,
    term: 'Acknowledgement Number (NCRP / 1930)',
    shortWhatItMeans: 'A statutory reference number (e.g. CF-728191 or 12-digit number) issued by the National Cyber Crime Reporting Portal (NCRP) or 1930 helpline.',
    whereToFindIt: 'Sent via SMS upon 1930 call completion and displayed on the cybercrime.gov.in complaint summary PDF.',
    whyNivaranNeedsIt: 'Banks require the official NCRP Acknowledgement Number to finalize fraud investigation memos and support fund lien disposals.'
  },
  {
    id: 'ncrp',
    numberIndex: 18,
    term: 'NCRP (National Cyber Crime Reporting Portal)',
    shortWhatItMeans: 'The central government portal (cybercrime.gov.in) operated by the Ministry of Home Affairs for citizens to report all cybercrimes in India.',
    whereToFindIt: 'Website: cybercrime.gov.in',
    whyNivaranNeedsIt: 'NIVARAN prepares your case package so you can submit a complete complaint directly on cybercrime.gov.in.'
  },
  {
    id: '1930',
    numberIndex: 19,
    term: '1930 (National Cyber Fraud Emergency Helpline)',
    shortWhatItMeans: 'The national toll-free helpline operationalized by the Indian Cybercrime Coordination Centre (I4C) for real-time reporting of financial cyber fraud.',
    whereToFindIt: 'Dial 1930 from your registered mobile phone.',
    whyNivaranNeedsIt: 'Calling 1930 within the first 2-3 hours ("Golden Hour") triggers inter-bank API alerts to freeze stolen funds at beneficiary bank nodes.'
  },
  {
    id: 'bank-grievance',
    numberIndex: 20,
    term: 'Bank Grievance Redressal Officer (GRO)',
    shortWhatItMeans: 'The senior designated official at each bank responsible for reviewing customer complaints that were unresolved or rejected by branch customer support.',
    whereToFindIt: 'Contact details published on each bank\'s official website under "Grievance Redressal".',
    whyNivaranNeedsIt: 'Stage 2 in the regulatory escalation ladder before approaching the Banking Ombudsman.'
  },
  {
    id: 'ombudsman',
    numberIndex: 21,
    term: 'RBI Banking Ombudsman (CMS Portal)',
    shortWhatItMeans: 'The statutory quasi-judicial authority appointed by the Reserve Bank of India to independently resolve customer grievances against banks and NBFCs at zero cost.',
    whereToFindIt: 'Online CMS Portal: cms.rbi.org.in',
    whyNivaranNeedsIt: 'Apex regulatory escalation authority if your bank rejects your fraud dispute or fails to respond within 30 days.'
  }
];

// -------------------------------------------------------------
// 2. RED FLAG DECODER SCENARIOS (7 Scenarios)
// -------------------------------------------------------------
export const RED_FLAG_DECODER_DATABASE: RedFlagDecoderItem[] = [
  {
    id: 'rf-account-block',
    scenario: '“They said my electricity / bank account / SIM will be blocked today.”',
    category: 'Urgency & Coercion',
    whyThisMatters: 'Artificial time pressure is designed to bypass your logical thinking and induce panic so you comply before verifying facts.',
    whatMayBeHappening: 'Scammers frequently impersonate state electricity boards (BESCOM, TNEB, MSEDCL), bank KYC desks, or telecom operators to manufacture fake emergencies.',
    whatNotToDo: 'Do not click links in the message. Do not call the private mobile number provided in the SMS. Do not pay any "verification fee".',
    whatToDoInstead: 'Check your official electricity board app, bank mobile app, or Bharat BillPay (BBPS) directly to confirm your real account status.'
  },
  {
    id: 'rf-install-app',
    scenario: '“They asked me to install an app (AnyDesk, QuickSupport, or an APK link).”',
    category: 'Device Compromise',
    whyThisMatters: 'Screen-sharing tools and third-party APKs allow remote attackers to see your mobile screen in real time and steal your passwords and OTPs.',
    whatMayBeHappening: 'The caller is attempting to gain remote control over your device or install spyware to intercept your banking SMS alerts.',
    whatNotToDo: 'Never install AnyDesk, TeamViewer, RustDesk, or download .apk files outside the official Google Play Store or Apple App Store.',
    whatToDoInstead: 'Disconnect the call immediately. If already installed, uninstall the app immediately and turn off Wi-Fi/mobile data.'
  },
  {
    id: 'rf-qr-receive',
    scenario: '“They asked me to scan a QR code to receive money or get a refund.”',
    category: 'Payment Reversal Trap',
    whyThisMatters: 'Scanning a QR code and entering your PIN ALWAYS DEBITS money from your account. A QR code is physically incapable of crediting funds to you.',
    whatMayBeHappening: 'A fraudulent buyer on OLX/Marketplace or fake support desk is trying to initiate a direct debit from your bank balance.',
    whatNotToDo: 'Do not scan the QR code. Do not enter your UPI PIN under any circumstance.',
    whatToDoInstead: 'Tell the sender that to receive money, they only need your UPI ID or phone number. Receiving money never requires scanning anything.'
  },
  {
    id: 'rf-nominal-rupee',
    scenario: '“They told me to send ₹1, ₹10 or ₹15 to verify my account or bill.”',
    category: 'Deceptive Authorization',
    whyThisMatters: 'The small nominal payment is a psychological decoy. Fraudsters either capture your card details on a fake payment gateway or trigger a high-value background transfer.',
    whatMayBeHappening: 'Known as the "Nominal Verification Trick", this method tricks you into approving an authentication flow while a much larger sum (e.g. ₹18,500) is debited.',
    whatNotToDo: 'Never pay nominal verification charges to unverified callers or through links received on chat apps.',
    whatToDoInstead: 'Pay verified bills exclusively on official government portals, bank apps, or authorized BBPS outlets.'
  },
  {
    id: 'rf-ask-otp',
    scenario: '“They asked for my OTP to cancel a fraudulent transaction or help me.”',
    category: 'Credential Theft',
    whyThisMatters: 'An OTP authorizes a transaction or password reset. Sharing an OTP is equivalent to handing over your house keys to a thief.',
    whatMayBeHappening: 'The caller has already initiated an unauthorized transaction or password reset and needs your OTP to finalize the theft.',
    whatNotToDo: 'Never read out, forward, or type an OTP into any form provided by a caller.',
    whatToDoInstead: 'Disconnect immediately. Call your bank fraud helpline directly using the number printed on the back of your debit card.'
  },
  {
    id: 'rf-video-call',
    scenario: '“They asked me to keep a video call open or stay on the line while paying.”',
    category: 'Digital Arrest / Isolation',
    whyThisMatters: 'Keeping you isolated on a continuous call prevents you from consulting family, friends, or your bank, maximizing psychological compliance.',
    whatMayBeHappening: 'Classic tactic in Digital Arrest, fake police/CBI impersonation, and high-pressure investment extortion scams.',
    whatNotToDo: 'Do not comply with demands to stay in an isolated room or keep cameras on. Do not transfer funds into "police verification escrow accounts".',
    whatToDoInstead: 'Disconnect the video call. Indian police and judicial agencies never conduct trials or demand bail money over WhatsApp/Skype.'
  },
  {
    id: 'rf-refund-pin',
    scenario: '“They said a refund requires me to enter my UPI PIN on a collect request.”',
    category: 'Collect Request Deception',
    whyThisMatters: 'A UPI PIN is an authorization credential for sending money out. Receiving money happens automatically without requiring your PIN.',
    whatMayBeHappening: 'The fraudster sent a UPI Collect Request disguised with a note like "REFUND_APPROVAL" hoping you will enter your PIN without reading.',
    whatNotToDo: 'Do not approve the collect request. Do not type your UPI PIN.',
    whatToDoInstead: 'Decline the collect request in your UPI app and report the requester profile as fraud.'
  }
];

// -------------------------------------------------------------
// 3. BEFORE YOU PAY CHECKLIST (7 Checkpoints)
// -------------------------------------------------------------
export const BEFORE_YOU_PAY_CHECKLIST = [
  { id: 'by-1', question: 'Do I know the recipient person or business independently?' },
  { id: 'by-2', question: 'Is this payment request expected and verifiable?' },
  { id: 'by-3', question: 'Does the recipient display name match who I intend to pay?' },
  { id: 'by-4', question: 'Was I pressured with urgency (e.g. 15-minute deadline or threats)?' },
  { id: 'by-5', question: 'Was I instructed to scan a QR code to "receive" money or cashbacks?' },
  { id: 'by-6', question: 'Was I asked for an OTP, password, or remote screen sharing code?' },
  { id: 'by-7', question: 'Did I receive this payment link through an unsolicited SMS or WhatsApp?' }
];

// -------------------------------------------------------------
// 4. WHAT EVIDENCE SHOULD YOU KEEP (12 Artifacts)
// -------------------------------------------------------------
export const EVIDENCE_PRESERVATION_GUIDE: EvidencePreservationItem[] = [
  {
    id: 'ev-p-1',
    name: 'Payment Receipt / Debit Screenshot',
    category: 'payment',
    whyItMatters: 'Contains the primary transaction proof: exact amount, timestamp, recipient VPA, and 12-digit UTR.',
    whereToFindIt: 'In your UPI app (Google Pay, PhonePe, Paytm) under Transaction History.',
    howToSaveIt: 'Take an uncropped full-screen screenshot showing the top and bottom of the receipt.'
  },
  {
    id: 'ev-p-2',
    name: 'Bank Debit Confirmation SMS',
    category: 'payment',
    whyItMatters: 'Official electronic record from your bank confirming the exact debit amount, debited account number, and NPCI reference.',
    whereToFindIt: 'In your phone default SMS inbox from your bank sender header (e.g. VM-HDFCBK, AX-SBIINB).',
    howToSaveIt: 'Take a screenshot of the SMS text and copy the raw SMS message text into your notes.'
  },
  {
    id: 'ev-p-3',
    name: 'Bank Statement PDF',
    category: 'payment',
    whyItMatters: 'Formal legal evidence required by police cyber cells and bank nodal dispute desks.',
    whereToFindIt: 'Download from your official mobile banking app or netbanking portal.',
    howToSaveIt: 'Save the original downloaded PDF without renaming or editing the file contents.'
  },
  {
    id: 'ev-p-4',
    name: 'WhatsApp / Chat Conversation Export',
    category: 'communication',
    whyItMatters: 'Demonstrates the deceptive claims, threats, and instructions given by the suspect before the debit.',
    whereToFindIt: 'Inside WhatsApp chat with the suspect.',
    howToSaveIt: 'Tap Contact Name → More → Export Chat → Without Media. Also take screenshots of key threat messages.'
  },
  {
    id: 'ev-p-5',
    name: 'Deceptive SMS Messages',
    category: 'communication',
    whyItMatters: 'Proves the origin of utility threats, fake job alerts, or courier delivery phishing links.',
    whereToFindIt: 'In your SMS inbox.',
    howToSaveIt: 'Take screenshots showing the full sender phone number or alphanumeric header.'
  },
  {
    id: 'ev-p-6',
    name: 'Caller Phone Number & Call Logs',
    category: 'identifier',
    whyItMatters: 'Allows telecom authorities (DoT / Sanchar Saathi) and cyber cells to trace the subscriber identity and block device IMEIs.',
    whereToFindIt: 'In your phone default Phone / Call Log app.',
    howToSaveIt: 'Screenshot your call log showing the exact incoming number, date, time, and call duration.'
  },
  {
    id: 'ev-p-7',
    name: 'Suspect UPI ID / VPA',
    category: 'identifier',
    whyItMatters: 'The destination identifier where money landed, allowing I4C to trigger an inter-bank freeze memo.',
    whereToFindIt: 'Displayed on the payment confirmation screen.',
    howToSaveIt: 'Note down the exact text (e.g. discom.billupdate.982@okaxis).'
  },
  {
    id: 'ev-p-8',
    name: 'Phishing Website / URL Links',
    category: 'identifier',
    whyItMatters: 'Enables CERT-In and DoT to take down malicious phishing servers and block APK download endpoints.',
    whereToFindIt: 'Inside the text message or email received.',
    howToSaveIt: 'Copy the full URL text (e.g. http://bescom-bill-update.xyz/download.apk).'
  },
  {
    id: 'ev-p-9',
    name: 'QR Code Image',
    category: 'payment',
    whyItMatters: 'Deconstructs the embedded payment payload and merchant aggregator account.',
    whereToFindIt: 'Saved in your phone photo gallery or chat media.',
    howToSaveIt: 'Keep the original uncompressed image file sent by the suspect.'
  },
  {
    id: 'ev-p-10',
    name: 'Bank Complaint Ticket / SR Number',
    category: 'payment',
    whyItMatters: 'Statutory proof that you notified your bank within the 3-day zero liability window.',
    whereToFindIt: 'Received in bank SMS or email confirmation after calling the fraud desk.',
    howToSaveIt: 'Save the reference string (e.g. HDFC-98127) and date/time of registration.'
  },
  {
    id: 'ev-p-11',
    name: '1930 / NCRP Acknowledgement Slip',
    category: 'communication',
    whyItMatters: 'Official government police acknowledgement required for final chargeback settlement.',
    whereToFindIt: 'Downloaded from cybercrime.gov.in portal.',
    howToSaveIt: 'Save the official Acknowledgement PDF slip.'
  },
  {
    id: 'ev-p-12',
    name: 'Email Communications',
    category: 'communication',
    whyItMatters: 'Shows full email headers (sender IP, DKIM/SPF verification) for corporate or fake invoice fraud.',
    whereToFindIt: 'Inside your email client (Gmail, Outlook).',
    howToSaveIt: 'Download the email as an .EML file or save as PDF showing sender email address.'
  }
];

// -------------------------------------------------------------
// 5. COMMON CONFUSIONS & MYTH VS REALITY
// -------------------------------------------------------------
export const COMMON_CONFUSIONS_DATABASE: CommonConfusionItem[] = [
  {
    id: 'cc-1',
    question: 'Can I receive money by entering my UPI PIN?',
    answer: 'No. A UPI PIN is strictly an authentication credential used to authorize debits (sending money). Receiving money into your bank account is automatic and never requires entering your PIN.',
    practicalTip: 'If anyone tells you to enter your PIN to receive cash or a refund, disconnect immediately.'
  },
  {
    id: 'cc-2',
    question: 'Should I scan a QR code to receive money or cashbacks?',
    answer: 'No. Scanning a QR code using a payment app initiates a payment action from your account. QR codes cannot deposit money into your account.',
    practicalTip: 'To receive payment, simply share your UPI ID or phone number. Never scan barcodes sent by buyers.'
  },
  {
    id: 'cc-3',
    question: 'Is a valid-looking UPI ID proof that a seller or utility is legitimate?',
    answer: 'No. Anyone can register a private UPI handle containing keywords like "discom.bill", "customercare", or "refund" on payment apps. Format validity is not proof of institutional authenticity.',
    practicalTip: 'Always verify utility bills inside authorized state apps or the official Bharat BillPay (BBPS) portal.'
  },
  {
    id: 'cc-4',
    question: 'Does an unknown phone number calling me automatically mean it is fraud?',
    answer: 'No. An unknown number is simply an unverified communication channel. However, if the caller demands urgent payments, PINs, OTPs, or app installations, treat it as high risk.',
    practicalTip: 'Always disconnect and call back on official verified toll-free numbers from the company\'s official website.'
  },
  {
    id: 'cc-5',
    question: 'If I report fraud to 1930, is my money guaranteed to be recovered?',
    answer: 'Recovery depends on the speed of reporting. If reported within the "Golden Hour" (first 2-3 hours), 1930 can trigger inter-bank liens before the fraudster withdraws funds. However, once funds are cashed out at ATMs or converted to crypto, recovery requires formal police investigation.',
    practicalTip: 'Speed is critical. Dial 1930 immediately with your 12-digit UTR number.'
  }
];

export const MYTH_VS_REALITY_DATABASE: MythVsRealityItem[] = [
  {
    id: 'mr-1',
    myth: '“Bank fraud prevention agents will call and ask for your OTP to stop an unauthorized transaction.”',
    reality: 'Banks NEVER ask for OTPs, CVVs, or netbanking passwords over the phone. Legitimate bank security teams block suspicious transactions internally without requiring your credentials.',
    impact: 'Sharing your OTP authorizes the very theft the fraudster is carrying out.'
  },
  {
    id: 'mr-2',
    myth: '“Entering a ₹1 test amount is safe to verify an online buyer.”',
    reality: 'Scammers use ₹1 test transactions to habituate victims to approving collect requests, followed immediately by high-value debits or remote access.',
    impact: 'Never approve unsolicited collect requests from unknown buyers.'
  },
  {
    id: 'mr-3',
    myth: '“Police or CBI officers can place you under \'Digital Arrest\' on a Skype/WhatsApp video call.”',
    reality: 'There is NO legal concept of "Digital Arrest" under Indian law. Indian police and judiciary never conduct interrogations or demand bail deposits over video calls.',
    impact: 'Disconnect video calls from self-proclaimed law enforcement immediately.'
  },
  {
    id: 'mr-4',
    myth: '“If I received an SMS saying money was credited, it is safe to refund the excess balance.”',
    reality: 'Scammers send fake SMS notifications formatted to mimic bank credit alerts while no real funds were transferred.',
    impact: 'Always verify your cleared balance directly inside your official bank app before taking any action.'
  }
];
